root_path: /srv/share4/datasets/wilds/data/
image_folder: camelyon17_v1.0/
nb_classes: 2
input_size: 96
workers: 4
pretrained_path: /srv/share4/asingh866/robust-ssl/pretrained/dino/dino_vitb16_cmlyn_lp_15000imgs_class.pth.tar
subset_file: /srv/share4/ksarangmath3/lsr/robust-ssl/subsets/camelyon17_subsets1/15000imgs_class.txt
model_location: /srv/share4/ksarangmath3/lsr/model-soups/soups/LP_dino_vitb16_camelyon_15000imgs_class_9_models/
name: LP_dino_vitb16_camelyon_15000imgs_class_9_models
model_name: deit_base
eval_type: lineval